In [3]:
import pandas as pd
import mysql.connector as mysql

In [4]:
connection = mysql.connect(
    host="localhost",
    user="root",
    passwd="Ruan81527733",
    database="mechanic",
)

df_services_raw = pd.read_sql("SELECT * FROM services_performed", connection)
df_problem_price = pd.read_sql("SELECT * FROM info_problem_price", connection)
df_price_services = pd.read_sql("SELECT * FROM info_price_services", connection)

C:\Users\ruans\AppData\Local\Temp\ipykernel_5600\2128138809.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_services_raw = pd.read_sql("SELECT * FROM services_performed", connection)
C:\Users\ruans\AppData\Local\Temp\ipykernel_5600\2128138809.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_problem_price = pd.read_sql("SELECT * FROM info_problem_price", connection)
C:\Users\ruans\AppData\Local\Temp\ipykernel_5600\2128138809.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_price_services = pd.read_sql("SELECT * FROM info_price_services", connection)

In [21]:
expensive_services_report = df_services_raw[df_services_raw["price"] > 20000]
expensive_services_report.head()

,services_performed_id,services,mechanic_id,vehicles_id,price,service_date
0,1,Troca dos discos e pastilhas de freio,7,1,45000.0,2028-03-28
2,3,Reparo da suspensão,5,3,25000.0,2029-11-08
3,4,Manutenção da refrigeração da transmissão,2,4,35000.0,2027-07-30

In [5]:
critical_transmission_report = df_problem_price.loc[(df_problem_price["price"] > 15000) & (df_problem_price["problem_description"].str.contains('transmissão'))]
critical_transmission_report.head()

,vehicles_id,model,problem_description,price
3,4,Lamborghini Aventador,Superaquecimento da transmissão ISR,35000.0

In [24]:
audited_mechanics = ['Pedro', 'Leticia', 'Valdemir']
mechanics_audit_report = df_price_services.loc[df_price_services["name"].isin(audited_mechanics)]
mechanics_audit_report.head()

       name                                    services
1   Leticia  Manutenção do arrefecimento da transmissão
2  Valdemir                         Reparo da suspensão
4     Pedro                 Reparo do vazamento de óleo

In [25]:
print(f'Expensive services report: {len(expensive_services_report)} records')
print(f'Critical transmission report: {len(critical_transmission_report)} records')
print(f'Mechanics audit report: {len(mechanics_audit_report)} records')

Expensive services report: 3 records
Critical transmission report: 1 records
Mechanics audit report: 3 records